# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright (c) 2018-current Ryan M. Lederman
version: ~> 1.0
language: c
branches:
  only:
  - master
env: MAKE=make
jobs:
  include:
    - os: linux
      dist: jammy
      arch: amd64
      compiler: gcc
    - os: linux
      dist: jammy
      arch: amd64
      compiler: clang
    - os: linux
      dist: jammy
      arch: arm64
      compiler: gcc
    - os: linux
      dist: jammy
      arch: arm64
      compiler: clang
    - os: linux
      dist: xenial
      arch: arm64
      compiler: gcc
    - os: linux
      dist: xenial
      arch: arm64
      compiler: clang
    - os: linux
      dist: bionic
      arch: arm64
      compiler: gcc
    - os: linux
      dist: bionic
      arch: amd64
      compiler: gcc
    - os: freebsd
      addons:
        pkg:
          - llvm16
      arch: amd64
      compiler: clang
      env:
        - MAKE=gmake
        - CC=/usr/local/bin/clang16
        - CXX=/usr/local/bin/clang++16
    - os: linux
      dist: bionic
      arch: s390x
      compiler: gcc
    - os: linux
      dist: bionic
      arch: s390x
      compiler: clang
    - os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc
    - os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: clang
    - os: freebsd
      addons:
        pkg:
          - gcc12
      arch: amd64
      compiler: gcc
      env:
        - MAKE=gmake
        - CC=/usr/local/bin/gcc
        - CXX=/usr/local/bin/g++
    - os: osx
      osx_image: xcode14.2
      arch: amd64
      compiler: clang
    - os: linux-ppc64le
      dist: trusty
      compiler: gcc
script:
  - ${MAKE:?} printvars || true
  - env ${MAKE:?} clean tests example
  - build/bin/sirtests
  - build/bin/sirexample
