version: ~> 1.0
language: c
branches:
  only:
  - master
  - syslog
dist: bionic
osx_image: xcode14.2
env: MAKE=make  
jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
    - os: linux
      arch: amd64
      compiler: clang
    - os: linux
      arch: arm64
      compiler: gcc
    - os: linux
      arch: arm64
      compiler: clang
    - os: freebsd
      arch: amd64
      compiler: gcc
      env: MAKE=gmake
    - os: osx      
      compiler: clang
script:
  - $MAKE clean tests example
  - build/bin/sirtests
  - build/bin/sirexample
install: skip
