version: ~> 1.0
language: c
branches:
  only:
  - master
jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
    - os: linux
      arch: amd64
      compiler: clang
    - os: linux
      arch: arm64
      compiler: gcc
    - os: linux
      arch: arm64
      compiler: clang
    - os: osx
      osx_image: xcode14.2
      compiler: clang
script:
  - make clean tests example
  - build/sirtests
  - build/sirexample

