.TH "cpp" 3 "Mon May 29 2023" "Version 2.1.1" "libsir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpp \- C++ wrapper
.PP
 \- C++ interface to libsir\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsir\fP"
.br
.RI "The one and only namespace for libsir\&. "
.in -1c
.SH "Detailed Description"
.PP 
C++ interface to libsir\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libsir from the source code\&.
