.TH "md__s_e_c_u_r_i_t_y" 3 "Mon May 29 2023" "Version 2.1.1" "libsir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__s_e_c_u_r_i_t_y \- Security Policy 
.PP

.SH "Supported Versions"
.PP
.PP
Any version after the first release (1\&.0) is qualified for vulnerability reporting\&.
.PP
.SH "Reporting a Vulnerability"
.PP
.PP
Please \fCcreate a new security vulnurability issue\fP and I will review it as quickly as I can\&. 
