.TH "sir" 3 "Mon May 29 2023" "Version 2.1.1" "libsir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sir \- The one and only namespace for libsir\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::basic_string< \fBsirchar_t\fP > \fBstring_t\fP"
.br
.RI "Technically, we could just use std::string, but template over \fBsirchar_t\fP in case it may be defined as a type other than char in the future (e\&.g\&., wchar_t)\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &strm, serializable const &p)"
.br
.RI "For std::ostream serialization\&. "
.in -1c
.SH "Detailed Description"
.PP 
The one and only namespace for libsir\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsir from the source code\&.
