.TH "sirconfig.h" 3 "Mon May 29 2023" "Version 2.1.1" "libsir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sirconfig.h \- Compile-time constants\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIR_LIBNAME\fP   'libsir'"
.br
.RI "The name of this library\&. "
.ti -1c
.RI "#define \fBSIR_TIMEFORMAT\fP   '%H:%M:%S'"
.br
.RI "The time stamp format string at the beginning of log messages\&. "
.ti -1c
.RI "#define \fBSIR_MSECFORMAT\fP   '\&.%03ld'"
.br
.RI "The format for the current millisecond in time stamps\&. "
.ti -1c
.RI "#define \fBSIR_LEVELFORMAT\fP   '[%s]'"
.br
.RI "The format for the human-readable logging level\&. "
.ti -1c
.RI "#define \fBSIR_PIDFORMAT\fP   '%d'"
.br
.RI "The format for the current process/thread ID, if no name is available/desired\&. "
.ti -1c
.RI "#define \fBSIR_PIDSEPARATOR\fP   '\&.'"
.br
.RI "The character to place between process and thread IDs\&. "
.ti -1c
.RI "#define \fBSIR_FOPENMODE\fP   'a'"
.br
.RI "The string passed to fopen/fopen_s for log files\&. "
.ti -1c
.RI "#define \fBSIR_FROLLSIZE\fP   (1024L * 1024L * 5L)"
.br
.RI "The size, in bytes, at which a log file will be rolled/archived\&. "
.ti -1c
.RI "#define \fBSIR_FHTIMEFORMAT\fP   '%H:%M:%S %a %d %b %y (%z)'"
.br
.RI "The time format string in file headers (see \fBSIR_FHFORMAT\fP)\&. "
.ti -1c
.RI "#define \fBSIR_FHFORMAT\fP   '\\n\\n\-\-\-\-\- %s %s \-\-\-\-\-\\n\\n'"
.br
.RI "The format string written to a log file when logging begins or the file is rolled/archived\&. "
.ti -1c
.RI "#define \fBSIR_FHBEGIN\fP   'session begin @'"
.br
.RI "The string included in \fBSIR_FHFORMAT\fP when a logging session begins\&. "
.ti -1c
.RI "#define \fBSIR_FHROLLED\fP   'archived as %s due to size @'"
.br
.RI "The string included in \fBSIR_FHFORMAT\fP when a file is rolled/archived due to size\&. "
.ti -1c
.RI "#define \fBSIR_FNAMETIMEFORMAT\fP   '%y\-%m\-%d\-%H%M%S'"
.br
.RI "The time format string for rolled/archived log files (see \fBSIR_FNAMEFORMAT\fP)\&. "
.ti -1c
.RI "#define \fBSIR_FNAMEFORMAT\fP   '%s\-%s%s'"
.br
.RI "The format string for rolled/archived log file names\&. "
.ti -1c
.RI "#define \fBSIRL_S_EMERG\fP   'emrg'"
.br
.RI "The human-readable form of the \fBSIRL_EMERG\fP level\&. "
.ti -1c
.RI "#define \fBSIRL_S_ALERT\fP   'alrt'"
.br
.RI "The human-readable form of the \fBSIRL_ALERT\fP level\&. "
.ti -1c
.RI "#define \fBSIRL_S_CRIT\fP   'crit'"
.br
.RI "The human-readable form of the \fBSIRL_CRIT\fP level\&. "
.ti -1c
.RI "#define \fBSIRL_S_ERROR\fP   'erro'"
.br
.RI "The human-readable form of the \fBSIRL_ERROR\fP level\&. "
.ti -1c
.RI "#define \fBSIRL_S_WARN\fP   'warn'"
.br
.RI "The human-readable form of the \fBSIRL_WARN\fP level\&. "
.ti -1c
.RI "#define \fBSIRL_S_NOTICE\fP   'noti'"
.br
.RI "The human-readable form of the \fBSIRL_NOTICE\fP level\&. "
.ti -1c
.RI "#define \fBSIRL_S_INFO\fP   'info'"
.br
.RI "The human-readable form of the \fBSIRL_INFO\fP level\&. "
.ti -1c
.RI "#define \fBSIRL_S_DEBUG\fP   'debg'"
.br
.RI "The human-readable form of the \fBSIRL_DEBUG\fP level\&. "
.ti -1c
.RI "#define \fBSIR_MAXFILES\fP   16"
.br
.RI "The maximum number of log files that may be registered\&. "
.ti -1c
.RI "#define \fBSIR_MAXMESSAGE\fP   2048"
.br
.RI "The maximum number of characters that may be included in one message, not including other parts of the output, like the timestamp and level\&. "
.ti -1c
.RI "#define \fBSIR_MAXTIME\fP   64"
.br
.RI "The size, in characters, of the buffer used to hold time format strings\&. "
.ti -1c
.RI "#define \fBSIR_MAXMSEC\fP   5"
.br
.RI "The size, in characters, of the buffer used to hold millisecond strings\&. "
.ti -1c
.RI "#define \fBSIR_MAXLEVEL\fP   7"
.br
.RI "The size, in characters, of the buffer used to hold level format strings\&. "
.ti -1c
.RI "#define \fBSIR_MAXNAME\fP   32"
.br
.RI "The size, in characters, of the buffer used to hold process/appname format strings\&. "
.ti -1c
.RI "#define \fBSIR_MAXPID\fP   16"
.br
.RI "The size, in characters, of the buffer used to hold process/thread IDs/names\&. "
.ti -1c
.RI "#define \fBSIR_MAXMISC\fP   7"
.br
.RI "The maximum number of whitespace and misc\&. "
.ti -1c
.RI "#define \fBSIR_MAXSTYLE_16_COLOR\fP   16"
.br
.RI "The minimum size, in characters, of the buffer used to hold a sequence of styling data in 16-color mode\&. "
.ti -1c
.RI "#define \fBSIR_MAXSTYLE\fP   \fBSIR_MAXSTYLE_16_COLOR\fP"
.br
.RI "For now, we will stick with just the one define for SIR_MAXOUTPUT, but as soon as 256-color and RGB color modes are implemented, we will need more than one of these\&. "
.ti -1c
.RI "#define \fBSIR_MAXOUTPUT\fP"
.br
.RI "The maximum size, in characters, of final formatted output\&. "
.ti -1c
.RI "#define \fBSIR_MAXERROR\fP   256"
.br
.RI "The maximum size, in characters, of an error message\&. "
.ti -1c
.RI "#define \fBSIR_ERRORFORMAT\fP   'Error in %s (%s:%u): '%s''"
.br
.RI "The format string for error messages returned by \fB_sir_geterror\fP\&. "
.ti -1c
.RI "#define \fBSIR_UNKNOWN\fP   '<unknown>'"
.br
.RI "The string that represents any unknown\&. "
.ti -1c
.RI "#define \fBSIR_NUMLEVELS\fP   8"
.br
.RI "The number of actual levels; \fBSIRL_NONE\fP, \fBSIRL_ALL\fP, and \fBSIRL_DEFAULT\fP are pseudo levels and end up being mapped (or not) to the other 8\&. "
.ti -1c
.RI "#define \fBSIR_BEGINSTYLE\fP   '\\x1b['"
.br
.RI "The prefix string used to begin a styling sequence in stdio output\&. "
.ti -1c
.RI "#define \fBSIR_ENDSTYLE\fP   \fBSIR_BEGINSTYLE\fP '0m'"
.br
.RI "The string used to reset any styling applied to text in stdio output\&. "
.ti -1c
.RI "#define \fBSIR_MSECCLOCK\fP   CLOCK_MONOTONIC"
.br
.RI "The default clock used to obtain the current millisecond from \fIclock_gettime\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Compile-time constants\&. 

This file and accompanying source code originated from https://github.com/aremmell/libsir\&. If you obtained it elsewhere, all bets are off\&.
.PP
\fBAuthor\fP
.RS 4
Ryan M\&. Lederman lederman@gmail.com 
.RE
.PP
\fBCopyright\fP
.RS 4
.RE
.PP
The MIT License (MIT)
.PP
Copyright (c) 2018 Ryan M\&. Lederman
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
.PP
Definition in file \fBsirconfig\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libsir from the source code\&.
