.TH "sirmutex.c" 3 "Mon May 29 2023" "Version 2.1.1" "libsir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sirmutex.c \- pthread and Win32 mutex\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'sirmutex\&.h'\fP
.br
\fC#include 'sirinternal\&.h'\fP
.br
\fC#include 'sirplatform\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fB_sirmutex_create\fP (\fBsirmutex_t\fP *mutex)"
.br
.RI "Creates/initializes a new mutex\&. "
.ti -1c
.RI "bool \fB_sirmutex_trylock\fP (\fBsirmutex_t\fP *mutex)"
.br
.RI "Determines if a mutex is locked without waiting\&. "
.ti -1c
.RI "bool \fB_sirmutex_lock\fP (\fBsirmutex_t\fP *mutex)"
.br
.RI "Attempts to lock a mutex and waits indefinitely\&. "
.ti -1c
.RI "bool \fB_sirmutex_unlock\fP (\fBsirmutex_t\fP *mutex)"
.br
.RI "Unlocks a previously locked mutex\&. "
.ti -1c
.RI "bool \fB_sirmutex_destroy\fP (\fBsirmutex_t\fP *mutex)"
.br
.RI "Destroys a mutex\&. "
.in -1c
.SH "Detailed Description"
.PP 
pthread and Win32 mutex\&. 

This file and accompanying source code originated from https://github.com/aremmell/libsir\&. If you obtained it elsewhere, all bets are off\&.
.PP
\fBAuthor\fP
.RS 4
Ryan M\&. Lederman lederman@gmail.com 
.RE
.PP
\fBCopyright\fP
.RS 4
.RE
.PP
The MIT License (MIT)
.PP
Copyright (c) 2018 Ryan M\&. Lederman
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
.PP
Definition in file \fBsirmutex\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libsir from the source code\&.
