.TH "sirtextstyle.h" 3 "Mon May 29 2023" "Version 2.1.1" "libsir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sirtextstyle.h \- stdio text styling\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'sirtypes\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIR_ESC_START\fP   '\\x1b['"
.br
.RI "Escape sequences: "
.ti -1c
.RI "#define \fBSIR_R_ARROW\fP   '\\xe2\\x86\\x92'"
.br
.RI "A couple fun characters that can be sent to stdio\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fB_sir_validstyle\fP (\fBsir_textstyle\fP style, uint32_t *pattr, uint32_t *pfg, uint32_t *pbg)"
.br
.RI "The maximum size of a color escape code sequence in bytes\&. "
.ti -1c
.RI "\fBsir_textstyle\fP \fB_sir_gettextstyle\fP (\fBsir_level\fP level)"
.br
.RI "Retrieves the override \fBsir_textstyle\fP for a \fBsir_level\fP if one is set\&. "
.ti -1c
.RI "\fBsir_textstyle\fP \fB_sir_getdefstyle\fP (\fBsir_level\fP level)"
.br
.RI "Retrieves the default \fBsir_textstyle\fP for a \fBsir_level\fP\&. "
.ti -1c
.RI "bool \fB_sir_settextstyle\fP (\fBsir_level\fP level, \fBsir_textstyle\fP style)"
.br
.RI "Sets the \fBsir_textstyle\fP for a \fBsir_level\fP\&. "
.ti -1c
.RI "bool \fB_sir_resettextstyles\fP (void)"
.br
.RI "Resets all per-level \fBsir_textstyle\fP to default\&. "
.ti -1c
.RI "uint16_t \fB_sir_getprivstyle\fP (uint32_t style)"
.br
.RI "Retrieves the opaque numeric value for a component part of a \fBsir_textstyle\fP\&. "
.ti -1c
.RI "bool \fB_sir_formatstyle\fP (\fBsir_textstyle\fP style, \fBsirchar_t\fP *buf, size_t size)"
.br
.RI "Combines component parts of a platform text style value into its final form\&. "
.in -1c
.SH "Detailed Description"
.PP 
stdio text styling\&. 

This file and accompanying source code originated from https://github.com/aremmell/libsir\&. If you obtained it elsewhere, all bets are off\&.
.PP
\fBAuthor\fP
.RS 4
Ryan M\&. Lederman lederman@gmail.com 
.RE
.PP
\fBCopyright\fP
.RS 4
.RE
.PP
The MIT License (MIT)
.PP
Copyright (c) 2018 Ryan M\&. Lederman
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
.PP
Definition in file \fBsirtextstyle\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libsir from the source code\&.
