.TH "test" 3 "Mon May 29 2023" "Version 2.1.1" "libsir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- Test List 
.PP

.IP "\fBGlobal \fBprint_test_error\fP (bool result, bool expected)\fP" 1c
 
.IP "\fBGlobal \fBsirtest_errorsanity\fP (void)\fP" 1c
Properly return valid codes and messages for all possible errors\&.  
.IP "\fBGlobal \fBsirtest_exceedmaxsize\fP (void)\fP" 1c
Properly handle messages that exceed internal buffer sizes\&.  
.IP "\fBGlobal \fBsirtest_failaftercleanup\fP (void)\fP" 1c
Properly handle calls after cleanup\&.  
.IP "\fBGlobal \fBsirtest_faildupefile\fP (void)\fP" 1c
Properly refuse to add a duplicate file\&.  
.IP "\fBGlobal \fBsirtest_failfilebadpermission\fP (void)\fP" 1c
Properly handle log file without appropriate permissions\&.  
.IP "\fBGlobal \fBsirtest_failinittwice\fP (void)\fP" 1c
Properly handle two initialization calls without corresponding cleanup\&.  
.IP "\fBGlobal \fBsirtest_failinvalidfilename\fP (void)\fP" 1c
Properly handle invalid log file name\&.  
.IP "\fBGlobal \fBsirtest_failnooutputdest\fP (void)\fP" 1c
Properly handle the lack of any output destinations\&.  
.IP "\fBGlobal \fBsirtest_failnulls\fP (void)\fP" 1c
Properly handle null/empty input\&.  
.IP "\fBGlobal \fBsirtest_failremovebadfile\fP (void)\fP" 1c
Properly refuse to remove a file that isn't added\&.  
.IP "\fBGlobal \fBsirtest_failsetinvalidstyle\fP (void)\fP" 1c
Properly handle invalid text style\&.  
.IP "\fBGlobal \fBsirtest_failwithoutinit\fP (void)\fP" 1c
Properly handle calls without initialization\&.  
.IP "\fBGlobal \fBsirtest_filecachesanity\fP (void)\fP" 1c
Properly handle adding and removing log files\&.  
.IP "\fBGlobal \fBsirtest_filesystem\fP (void)\fP" 1c
Ensure the proper functionality of portable filesystem implementation\&.  
.IP "\fBGlobal \fBsirtest_initcleanupinit\fP (void)\fP" 1c
Properly handle initialization, cleanup, re-initialization\&.  
.IP "\fBGlobal \fBsirtest_mthread_race\fP (void)\fP" 1c
Properly handle multiple threads competing for locked sections\&.  
.IP "\fBGlobal \fBsirtest_os_log\fP (void)\fP" 1c
Properly open, configure, and send messages to os_log()\&. 
.IP "\fBGlobal \fBsirtest_perf\fP (void)\fP" 1c
Performance evaluation\&.  
.IP "\fBGlobal \fBsirtest_rollandarchivefile\fP (void)\fP" 1c
Properly roll/archive a file when it hits max size\&.  
.IP "\fBGlobal \fBsirtest_syslog\fP (void)\fP" 1c
Properly open, configure, and send messages to syslog()\&.  
.IP "\fBGlobal \fBsirtest_textstylesanity\fP (void)\fP" 1c
Properly style stdio output for each level, and handle style overrides\&.  
.IP "\fBGlobal \fBsirtest_updatesanity\fP (void)\fP" 1c
Properly update levels/options at runtime\&. 
.PP

