.TH "tests/tests.h" 3 "Mon May 29 2023" "Version 2.1.1" "libsir" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/tests.h \- libsir test suite\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sir\&.h>\fP
.br
\fC#include <sirerrors\&.h>\fP
.br
\fC#include <sirfilecache\&.h>\fP
.br
\fC#include <sirinternal\&.h>\fP
.br
\fC#include <sirhelpers\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsir_test\fP"
.br
.RI "Map a test to a human-readable description\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef bool(* \fBsir_test_fn\fP) (void)"
.br
.RI "Function signature for a single test\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsirtest_mthread_race\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_exceedmaxsize\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_filecachesanity\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_failsetinvalidstyle\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_failnooutputdest\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_failinvalidfilename\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_failfilebadpermission\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_failnulls\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_failwithoutinit\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_failinittwice\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_failaftercleanup\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_initcleanupinit\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_faildupefile\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_failremovebadfile\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_rollandarchivefile\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_errorsanity\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_textstylesanity\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_perf\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_updatesanity\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_syslog\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_os_log\fP (void)"
.br
.ti -1c
.RI "bool \fBsirtest_filesystem\fP (void)"
.br
.ti -1c
.RI "bool \fBprint_test_error\fP (bool result, bool expected)"
.br
.in -1c
.SH "Detailed Description"
.PP 
libsir test suite\&. 

This file and accompanying source code originated from https://github.com/aremmell/libsir\&. If you obtained it elsewhere, all bets are off\&.
.PP
\fBAuthor\fP
.RS 4
Ryan M\&. Lederman lederman@gmail.com 
.RE
.PP
\fBCopyright\fP
.RS 4
.RE
.PP
The MIT License (MIT)
.PP
Copyright (c) 2018 Ryan M\&. Lederman
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
.PP
.PP
.PP
 
.PP
Definition in file \fBtests\&.h\fP\&.
.SH "Data Structure Documentation"
.PP 
.SH "struct sir_test"
.PP 
Map a test to a human-readable description\&. 
.PP
Definition at line \fB95\fP of file \fBtests\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "bool print_test_error (bool result, bool expected)"

.PP
\fBTest\fP
.RS 4

.RE
.PP
.PP
bool sirtest_xxxx(void); 
.PP
Definition at line \fB958\fP of file \fBtests\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libsir from the source code\&.
